services:
    development:
      container_name: "app-dev-shokworks"
      image: dev
      build:
        context: .
        target: development
      env_file:
        - .env.development
      ports:
        - "3000:3000"
      networks:
        - shokworks-network
      volumes:
        - ./:/app
        - /app/node_modules
      restart: unless-stopped

    production:
      container_name: "app-prod-shokworks"
      image: prod
      build:
        context: .
        target: production
      env_file:
        - .env.production
      ports:
        - "8000:8000"
      networks:
        - shokworks-network
      restart: unless-stopped

networks:
  shokworks-network:
    driver: bridge
